resources:
- name: every-working-day
  type: time
  source:
    start: 9:00 AM
    stop: 10:00 AM
    location: Europe/Dublin
    days: [Monday, Tuesday, Wednesday, Thursday, Friday]

- name: mooderator-api
  type: git
  source:
    uri: https://github.com/jhvhs/mooderator-api.git
    branch: master

jobs:
- name: slack-stats
  plan:
  - get: every-working-day
    trigger: true
  - get: mooderator-api
    trigger: false
  - task: slack-stats
    file: mooderator-api/ci/slack-stats.yml
    params:
      WEBHOOK_SUFFIX: ((webhook-suffix))
      API_URL: ((mooderator-api-url))
      WEB_URL: ((mooderator-web-url))